/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPlonkVerifier } from "./IPlonkVerifier";
export type { IZekoGenerativeNFT } from "./IZekoGenerativeNFT";
export type { PrivateAirdrop } from "./PrivateAirdrop";
