/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAirdropContract } from "./IAirdropContract";
export type { ZekoGenerativeNFT } from "./ZekoGenerativeNFT";
