/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IPlonkVerifier,
  IPlonkVerifierInterface,
} from "../IPlonkVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
      {
        internalType: "uint256[]",
        name: "pubSignals",
        type: "uint256[]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IPlonkVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IPlonkVerifierInterface {
    return new utils.Interface(_abi) as IPlonkVerifierInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPlonkVerifier {
    return new Contract(address, _abi, signerOrProvider) as IPlonkVerifier;
  }
}
