/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IZekoGenerativeNFT,
  IZekoGenerativeNFTInterface,
} from "../IZekoGenerativeNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IZekoGenerativeNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IZekoGenerativeNFTInterface {
    return new utils.Interface(_abi) as IZekoGenerativeNFTInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IZekoGenerativeNFT {
    return new Contract(address, _abi, signerOrProvider) as IZekoGenerativeNFT;
  }
}
