/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as privateAirdropSol from "./PrivateAirdrop.sol";
export type { privateAirdropSol };
import type * as zekoGenerativeNftSol from "./ZekoGenerativeNFT.sol";
export type { zekoGenerativeNftSol };
import type * as compiled from "./compiled";
export type { compiled };
